# Generated by Django 4.0.4 on 2022-06-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accompainingsheettbl_complecttbl_conclusiontbl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gk', models.CharField(blank=True, max_length=30, null=True)),
                ('project', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.CharField(blank=True, max_length=30, null=True)),
                ('complect', models.CharField(blank=True, max_length=30, null=True)),
                ('sn', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('manufactur', models.CharField(blank=True, max_length=30, null=True)),
                ('secretnum', models.CharField(blank=True, max_length=30, null=True)),
                ('mark', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
